-- Create the app_versions table
create table if not exists app_versions (
  id bigint generated by default as identity primary key,
  version text not null, -- e.g., '1.0.9'
  build_number integer, -- Optional: for easier comparison if you use build numbers (e.g., 9)
  platform text not null check (platform in ('ios', 'android')),
  mandatory boolean default false,
  store_url text, -- URL to the App Store or Google Play Store
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table app_versions enable row level security;

-- Create a policy that allows anyone to read the versions (public access)
create policy "Enable read access for all users"
on app_versions for select
using (true);

-- Insert initial data (example)
-- You should update these values with your actual latest versions
insert into app_versions (version, platform, mandatory, store_url)
values 
  ('1.0.9', 'android', false, 'https://play.google.com/store/apps/details?id=com.magnate.mobile'),
  ('1.0.9', 'ios', false, 'https://apps.apple.com/app/id...');
